<a href="https://colab.research.google.com/github/gokadagaya/fittrack-project--2601920-/blob/main/Question2_Pandas_Selection_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Firstly i created a data which was provided and used a dictionary of list for cleanest approch.and printed the pandas dataframe as employee_data.

In [3]:
import pandas as pd

data = {
    'EmployeeID': [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    'Name': ['Sarah', 'Michael', 'Jennifer', 'David', 'Lisa',
             'James', 'Emma', 'Robert', 'Sophia', 'William'],
    'Department': ['Engineering', 'Sales', 'Marketing', 'Engineering', 'HR',
                   'Sales', 'Engineering', 'Marketing', 'Sales', 'HR'],
    'Salary': [85000, 62000, 71000, 92000, 58000,
               68000, 78000, 75000, 65000, 60000],
    'Performance Score': [4, 3, 5, 5, 4, 4, 3, 4, 5, 3],
    'Years of Service': [5, 3, 7, 8, 4, 6, 2, 5, 4, 3]
}
employee_data=pd.DataFrame(data)
employee_data

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
1,202,Michael,Sales,62000,3,3
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
4,205,Lisa,HR,58000,4,4
5,206,James,Sales,68000,4,6
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5
8,209,Sophia,Sales,65000,5,4
9,210,William,HR,60000,3,3

Select and display only the 'Name', 'Department', and 'Salary' columns

selecting only name , department and salary columns by the original dataframe employee_data

In [4]:
selected_columns=employee_data[['Name','Department','Salary']]
selected_columns

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

Use iloc to display the employee at row position 5

taking original dataframe employee_data and using iloc(position based)

In [5]:
employee=employee_data.iloc[5]
employee

EmployeeID             206
Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 5, dtype: object

Use loc to display the employee with EmployeeID 208

loc to filter the row where EmployeeID is 208 and returns only the Name and EmployeeID columns.

In [16]:
emp=employee_data.loc[employee_data['EmployeeID']==208,['Name','EmployeeID']]
emp

     Name  EmployeeID
7  Robert         208

Filter and display all employees from the 'Engineering' department

uses Pandas query() to filter and return only the rows where the Department column equals 'Engineering'.

In [18]:
filtering=employee_data.query("Department =='Engineering'")
filtering

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

Filter and display all employees with Salary greater than 70000

uses Pandas query() to filter and return only the salary>7000

In [19]:
employees=employee_data.query("Salary>70000")
employees

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

Filter and display employees from 'Sales' department with Performance Score >= 4

In [21]:
employees=employee_data[(employee_data['Department']=='Sales')&(employee_data['Performance Score']>=4)]
employees

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

Sort the entire DataFrame by Salary in descending order and display the top 3 highest-paid employees

In [11]:
highest_paid_employees = employee_data.sort_values(by='Salary', ascending=False).head(3)
highest_paid_employees

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Engineering   92000                  5                 8
0         201  Sarah  Engineering   85000                  4                 5
6         207   Emma  Engineering   78000                  3                 2

Sort by Department (ascending) and then by Salary (descending) within each department

In [12]:
sorting=employee_data.sort_values(by=['Department','Salary'],ascending=[True,False])
sorting

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3